name: JBEnchants
version: '${project.version}'
api-version: 1.20
main: de.exo.jbenchants.Main
authors: [Exoskelett]
depend: [NBTAPI]

commands:
  jbe:
  test:
  cleanser:
  crystal:
  dust:
  repairscroll: