name: JBEnchants
version: '${project.version}'
api-version: 1.19
main: de.exo.jbenchants.Main
authors: [Exoskelett]
depend: [NBTAPI, PlaceholderAPI, WorldEdit, WorldGuard]

commands:
  jbe:
  jbdebug:
  cleanser:
  crystal:
  crystals:
  dust:
  enchants:
  repairscroll: